[ember]
id = "tutorial"
name = "tutorial"
version = "0.0.1"
categories = ["game/other"]

[messages.Input]
description = "Describes the input state of the player."
[messages.Input.fields]
direction = "Vec2"
mouse_delta = "Vec2"
