[[pipelines]]
type = "Models"
sources = ["X Bot.fbx"]

[[pipelines]]
type = "Models"
sources = ["Run Forward.fbx"]

[[pipelines]]
type = "Models"
sources = ["Rifle Aiming Idle.fbx"]

[[pipelines]]
type = "Models"
sources = ["red.glb"]
